[tool.poetry]
name = "bifrost-rpc"
version = "0.1.0"
description = ""
license = "MIT"
authors = []
packages = [
    { include = "bifrostrpc" }
]

[tool.poetry.dependencies]
python = "^3.6"
typing-extensions = {version = "^3.7.4", python = "<3.8"}

[tool.poetry.dev-dependencies]
mypy = "^0.770"
