on: [push, pull_request]

jobs:
    verify_requirements_exported:
        name: "Ensure requirements.txt has been exported"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup python
              uses: actions/setup-python@v2
              with:
                python-version: 3.8
            - run: pip3 install --user poetry
            - run: tests/bin/ensure_requirements_txt_exported
              #    test_python_36:
              #        name: "py.test under py3.6"
              #        container: python3.6
              #    test_python_37:
              #        name: "py.test under py3.7"
              #        container: python3.7
              #    test_python_38:
              #        name: "py.test under py3.8"
              #        container: python3.8
