on:
  push:
    branches:
      - master
  pull_request:
    # run on all pull requests

jobs:
    verify_requirements_exported:
        name: "Ensure requirements.txt has been exported"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup python
              uses: actions/setup-python@v2
              with:
                python-version: 3.8
            - run: sudo python3 -m pip install poetry
            - run: tests/bin/ensure_requirements_txt_exported

    linting:
        name: "Linters / Static Checkers"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup python
              uses: actions/setup-python@v2
              with:
                python-version: 3.8
            - run: pip install -r requirements_dev.txt
            - run: mypy .
            - run: flake8 bifrostrpc tests
            - run: pylint bifrostrpc

    unit_tests:
      name: "Pytest"
      runs-on: ubuntu-latest
      strategy:
        matrix:
            python-version:
                - 3.8
                - 3.9
                # XXX: this project doesn't work on 3.10 and above, presumably because python
                # types are no longer resolved at runtime
                # - "3.10"
      steps:
        - uses: actions/checkout@v2
        - name: Setup python
          uses: actions/setup-python@v2
          with:
            python-version: ${{matrix.python-version}}
        - run: python -m pip install -r requirements_dev.txt
        - run: python -m pip install .
        - run: py.test
